wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1660836503.660471
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 23
      4: 3.9.10
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
